SportApp/Web/SportApp.Web/Areas/Administration/Controllers/CategoriesController.cs
namespace SportApp.Web.Areas.Administration.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using Microsoft.EntityFrameworkCore;
    using SportApp.Data;
    using SportApp.Data.Common.Repositories;
    using SportApp.Data.Models;
    using SportApp.Services.Data;
    using SportApp.Web.ViewModels.Administration.Categories;

    [Area("Administration")]
    public class CategoriesController : AdministrationController
    {
        private readonly ICategoriesService categoryService;

        public CategoriesController(ICategoriesService categoryService)
        {
            this.categoryService = categoryService;
        }

        // GET: Administration/Categories
        public IActionResult Index()
        {
            var model = this.categoryService.All();
            return this.View(model);
        }

        // GET: Administration/Categories/Create
        public IActionResult Create()
        {
            return this.View();
        }

        // POST: Administration/Categories/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CategoryInputModel input)
        {
            if (this.ModelState.IsValid)
            {
                await this.categoryService.CreateAsync(input);
                return this.RedirectToAction(nameof(this.Index));
            }

            return this.View(input);
        }

        // GET: Administration/Categories/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
            var category = await this.categoryService.GetByIdAsync(id);
            if (category == null)
            {
                return this.RedirectToAction(nameof(this.Index));
            }

            return this.View(category);
        }

        // POST: Administration/Categories/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, EditCategoryInputModel input)
        {
            if (this.ModelState.IsValid)
            {
                try
                {
                    await this.categoryService.UpdateAsync(id, input);
                }
                catch (DbUpdateConcurrencyException)
                {
                    return this.View(input);
                }

                return this.RedirectToAction(nameof(this.Index));
            }

            return this.View(input);
        }

        // GET: Administration/Categories/Delete/5
        public async Task<IActionResult> Delete(int id)
        {
            var category = await this.categoryService.GetByIdAsync(id);
            if (category == null)
            {
                return this.NotFound();
            }

            return this.View(category);
        }

        // POST: Administration/Categories/Delete/5
        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await this.categoryService.DeleteAsync(id);
            return this.RedirectToAction(nameof(this.Index));
        }
    }
}

SportApp/Web/SportApp.Web/Controllers/ChatController.cs
namespace SportApp.Web.Controllers
{
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using SportApp.Services.Data;
    using SportApp.Web.ViewModels;

    public class ChatController : BaseController
    {
        private readonly IMessageService messageService;

        public ChatController(IMessageService messageService)
        {
            this.messageService = messageService;
        }

        [Authorize]
        public IActionResult Chat()
        {
            var model = new ChatViewModel
            {
                Messages = this.messageService.GetAll(),
            };

            return this.View(model);
        }

        [Authorize]
        public async Task<IActionResult> Delete(int id)
        {
            var message = this.messageService.GetById(id);
            if (message == null)
            {
                return this.RedirectToAction(nameof(this.Chat));
            }

            if (this.User.Identity.Name == message.User)
            {
                await this.messageService.DeleteAsync(id);
            }

            return this.RedirectToAction(nameof(this.Chat));
        }
    }
}

SportApp/Web/SportApp.Web/Controllers/GroupTrainingsController.cs
namespace SportApp.Web.Controllers
{
    using System;
    using System.Data;
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using SportApp.Common;
    using SportApp.Data.Models;
    using SportApp.Services.Data;
    using SportApp.Web.ViewModels.GroupTrainings;
    using SportApp.Web.ViewModels.Trainers;

    public class GroupTrainingsController : Controller
    {
        private readonly IGroupTrainingsService groupTrainingsService;
        private readonly UserManager<ApplicationUser> userManager;

        public GroupTrainingsController(
            IGroupTrainingsService groupTrainingsService,
            UserManager<ApplicationUser> userManager)
        {
            this.groupTrainingsService = groupTrainingsService;
            this.userManager = userManager;
        }

        public async Task<IActionResult> All()
        {
            var viewModel = new GroupTrainingsListViewModel
            {
                GroupTrainings = await this.groupTrainingsService.GetAllAsync<GroupTrainingViewModel>(),
            };

            return this.View(viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> All(string looking)
        {
            var viewModel = new GroupTrainingsListViewModel
            {
                GroupTrainings = await this.groupTrainingsService.GetSearchedTrainingsAsync<GroupTrainingViewModel>(looking),
            };

            return this.View(viewModel);
        }

        [Authorize(Roles = GlobalConstants.TrainerRoleName)]
        public IActionResult Create()
        {
            var viewModel = new CreateGroupTrainingInputModel();
            return this.View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = GlobalConstants.TrainerRoleName)]
        public async Task<IActionResult> Create(CreateGroupTrainingInputModel input)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(input);
            }

            try
            {
                var user = await this.userManager.GetUserAsync(this.User);
                input.TrainerUserId = user.Id;
                await this.groupTrainingsService.CreateAsync(input);
            }
            catch (Exception ex)
            {
                this.ModelState.AddModelError(string.Empty, ex.Message);
                return this.View(input);
            }

            return this.Redirect("/");
        }

        [Authorize(Roles = GlobalConstants.TrainerRoleName)]
        public async Task<IActionResult> Edit(int id)
        {
            var user = await this.userManager.GetUserAsync(this.User);
            var model = this.groupTrainingsService.GetById<EditGroupTrainingInputModel>(id);

            if (model == null)
            {
                return this.RedirectToAction(nameof(this.All));
            }

            if (model.TrainerUserId == user.Id)
            {
                return this.View(model);
            }

            return this.RedirectToAction(nameof(this.All));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = GlobalConstants.TrainerRoleName)]
        public async Task<IActionResult> Edit(int id, EditGroupTrainingInputModel model)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(model);
            }

            if (model.TrainerUserId == this.userManager.GetUserId(this.User))
            {
                await this.groupTrainingsService.UpdateAsync(id, model);
                return this.RedirectToAction(nameof(this.All));
            }

            return this.NotFound();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = GlobalConstants.TrainerRoleName)]
        public async Task<IActionResult> Delete(int id)
        {
            var model = this.groupTrainingsService.GetById<DeleteModel>(id);
            if (model.TrainerUserId == this.userManager.GetUserId(this.User))
            {
                await this.groupTrainingsService.DeleteAsync(id);
                return this.RedirectToAction(nameof(this.All));
            }

            return this.NotFound();
        }

        [Authorize]
        public async Task<IActionResult> SignForTraining(int id)
        {
            var user = await this.userManager.GetUserAsync(this.User);
            var result = await this.groupTrainingsService.SignInForTrainingAsync(id, user.Id);
            if (!result)
            {
                return this.RedirectToAction(nameof(this.All));
            }

            return this.RedirectToAction(nameof(this.All));
        }

        [Authorize(Roles = GlobalConstants.TrainerRoleName)]
        public async Task<IActionResult> SignInUsers(int id)
        {
            var bookedUsers = await this.groupTrainingsService.SighnInUsersAsync(id);
            if (bookedUsers == null)
            {
                return this.RedirectToAction(nameof(this.All));
            }

            return this.View(bookedUsers);
        }
    }
}

SportApp/Web/SportApp.Web/Controllers/VideosController.cs
namespace SportApp.Web.Controllers
{
    using System;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Hosting;
    using Microsoft.AspNetCore.Mvc;
    using SportApp.Common;
    using SportApp.Services.Data;
    using SportApp.Web.ViewModels;

    public class VideosController : Controller
    {
        private readonly IWebHostEnvironment environment;
        private readonly IVideoSurvice videoSurvice;

        public VideosController(IWebHostEnvironment environment, IVideoSurvice videoSurvice)
        {
            this.environment = environment;
            this.videoSurvice = videoSurvice;
        }

        [Authorize]
        public async Task<IActionResult> All()
        {
            var videos = new ListWithVideosViewModel
            {
                Videos = await this.videoSurvice.GetAllAsync(),
            };

            return this.View(videos);
        }

        [Authorize(Roles = GlobalConstants.TrainerRoleName)]
        public IActionResult Add()
        {
            var videoModel = new VideoModel();
            return this.View(videoModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = GlobalConstants.TrainerRoleName)]
        public async Task<IActionResult> Add(VideoModel model)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(model);
            }

            try
            {
                await this.videoSurvice.CreateAsync(model, $"{this.environment.WebRootPath}");
            }
            catch (Exception ex)
            {
                this.ModelState.AddModelError(string.Empty, ex.Message);
                return this.View(model);
            }

            return this.RedirectToAction("All");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = GlobalConstants.AdministratorRoleName)]
        public async Task<IActionResult> Delete(string id)
        {
            await this.videoSurvice.DeleteAsync(id);
            return this.RedirectToAction(nameof(this.All));
        }
    }
}

SportApp/Web/SportApp.Web/Areas/Administration/Views/Shared/_Layout.cshtml
@using SportApp.Common
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@this.ViewData["Title"] - @GlobalConstants.SystemName</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" asp-append-version="true" />
    <link href="~/css/style.css" rel="stylesheet" asp-append-version="true" />
    <link href="~/css/classy-nav.min.css" rel="stylesheet" asp-append-version="true" />
    <link href="~/lib/fontawesome/css/all.css" rel="stylesheet" asp-append-version="true" />
    <link href="~/lib/fontawesome/css/all.min.css" rel="stylesheet" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">@GlobalConstants.SystemName</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Trainers" asp-action="All">Trainers</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="GroupTrainings" asp-action="All">GroupTrainings</a>
                        </li>
                        @if (this.User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Chat" asp-action="Chat">Chat Room</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Videos" asp-action="All">Video Room</a>
                            </li>
                        }
                        @if (this.User.IsInRole(GlobalConstants.AdministratorRoleName))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Trainers" asp-action="Create">Add Trainer</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Administration" asp-controller="Categories" asp-action="Index">Categories Admin</a>
                            </li>
                        }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @this.RenderBody()
        </main>
    </div>
    
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; @DateTime.Now.Year - @GlobalConstants.SystemName - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js" asp-append-version="true"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js" asp-append-version="true"></script>
    <script src="~/lib/signalr//dist//browser/signalr.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/dist/jquery.validate.unobtrusive.min.js" asp-append-version="true"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js" asp-append-version="true"></script>
    <script src="~/js/site.min.js" asp-append-version="true"></script>
    <script src="~/js/jquery.override-validator.js"></script>
    @await this.RenderSectionAsync("Scripts", required: false)
</body>
</html>